config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #mount Ckeditor::Engine => '/ckeditor'
  resources :banners
  get 'survey/index'
  get 'survey/done'
  get 'service/index'
  resources :denial_reasons, path: 'admin/denial_reasons'
  get 'moderator/index', to: 'moderator#index', as: :moderate_submissions
  get 'moderator/approve', to: 'moderator#approve', as: :approve_submission
  get 'moderator/denial', to: 'moderator#denial', as: :denial_submission
  post 'moderator/deny', to: 'moderator#deny', as: :deny_submission
  get 'moderator/denied', to: 'moderator#denied', as: :denied_submissions
  get 'moderator/users', to: 'moderator#users', as: :moderator_users

  resources :activities

  get 'resourcings/remove_resourcing', to: 'resourcings#remove_resourcing', as: :remove_resourcing
  resources :resourcings
  get 'resources/log_event', to: 'resources#log_event', as: :log_event
  get 'resources/download', to: 'resources#download', as: :download_resource

  resources :user_types, path: 'admin/user_types'
  resources :organization_types, path: 'admin/organization_types'

  #mount RailsAdmin::Engine => '/cpanel', as: 'rails_admin'

  #resources :batches
  #resources :categories
  resources :tags, path: 'admin/tags'
  get 'tags/guide', to: 'tags#show_guide', as: :show_guide
  resources :tag_types, path: 'admin/tag_types'
  resources :featured_searches
  resources :announcements, path: 'admin/announcements'
  get 'announcements', to: 'announcements#public_announcements', as: :public_announcements
  get 'announcements/:id', to: 'announcements#show_announcement', as: :show_announcement

  resources :cops, path: 'admin/cops'
  get 'cops/:id', to: 'cops#show_cop', as: :show_cop
  get 'cop_event_email_info/:id', to: 'cops#show_event_email_info', as: :cop_event_email_info
  get 'cop_email_info/:id', to: 'cops#show_email_info', as: :cop_email_info
  
  resources :events, path: 'admin/events'
  get 'events', to: 'events#public_events', as: :public_events
  get 'events/:id', to: 'events#show_event', as: :show_event

  get 'faq/index', to: 'faq#index', as: :faq
  resources :users_organizations
  put 'usersorganizations/update_org_role', to: 'users_organizations#update_org_role', as: :update_org_role

  get 'data/csv', to: 'data#csv', as: :data_csv
  #get 'contact', to: 'contact#index', as: :contact
  #get "contact/index"
  get 'about', to: 'about#index', as: :about
  get 'about/types', to: 'about#types', as: :about_resource_types
  get 'about/new_users', to: 'about#new_users', as: :new_users
  get 'about/disclaimer', to: 'about#disclaimer', as: :disclaimer
  get 'about/access_denied', to: 'about#access_denied', as: :access_denied
  get 'about/index'
  get 'admin/index'
  post 'admin/invite_user', to: 'admin#invite_user', as: :invite_user
  get 'admin/contest', to: 'admin#contest', as: :admin_contest
  get 'admin/resource_ratings', to: 'admin#resource_ratings', as: :resource_ratings
  get 'admin/collection_ratings', to: 'admin#collection_ratings', as: :collection_ratings
  get 'admin/survey_report', to: 'admin#survey_report', as: :survey_report
  get 'admin/contest_report', to: 'admin#contest_report', as: :contest_report
  get 'admin/access_report', to: 'admin#access_report', as: :access_report
  #get 'admin/manage_tags', to: 'admin#manage_tags', as: :manage_tags
  #get 'admin/delete_tag', to: 'admin#delete_tag', as: :delete_tag
  #get 'admin/edit_tag', to: 'admin#edit_tag', as: :edit_tag
  #get 'admin/new_tag', to: 'admin#new_tag', as: :new_tag
  #post 'admin/update_tag', to: 'admin#update_tag', as: :update_tag
  get 'admin/orgs', to: 'admin#orgs', as: :orgs
  get 'admin/upload_files', to: 'admin#upload_files', as: :upload_files
  get 'admin/private_resources', to: 'admin#private_resources', as: :private_resources
  get 'admin/pending_submissions', to: 'admin#pending_submissions', as: :pending_submissions
  post 'admin/process_uploaded_files', to: 'admin#process_uploaded_files', as: :process_uploaded_files
  get 'admin/fix_resource_collections_menu', to: 'admin#fix_resource_collections_menu', as: :fix_resource_collections_menu
  get 'admin/fix_resource_collections', to: 'admin#fix_resource_collections', as: :fix_resource_collections

  #get 'ViewerJS', :to => redirect('/ViewerJS/index.html')
  get 'resources/rate_resource', to: 'resources#rate_resource', as: :rate_resource
  get 'resources/not_found', to: 'resources#not_found', as: :resources_not_found
  get 'resources/preview/:id', to: 'resources#preview', as: :resource_preview
  resources :resources

  get 'searches/update_search', to: 'searches#update_search', as: :update_search
  resources :searches

  get 'collections/not_found', to: 'collections#not_found', as: :collections_not_found
  get 'collections/rate_collection', to: 'collections#rate_collection', as: :rate_collection
  resources :collections do
    resources :resourcings
  end
  get 'about/no_approved_org', to: 'about#no_approved_org', as: :no_approved_orgs

  resources :types

  resources :licenses

  get 'organizations/not_found', to: 'organizations#not_found', as: :organization_not_found
  get 'organizations/add_user/:organization', to: 'organizations#add_user', as: :organization_add_user
  get 'organizations/apply', to: 'organizations#apply', as: :organization_apply
  get 'organizations/edit_user/:userorg', to: 'organizations#edit_user', as: :users_organizations_edit_role
  get 'organizations/approve_organization/:organization', to: 'organizations#approve_organization', as: :organization_approve
  get 'organizations/process_application', to: 'organizations#process_application', as: :organization_process_application
  match 'organizations/process_application_denial' => 'organizations#process_application_denial', :as => :organizations_process_application_denial, :via => 'post'
  match 'organizations/add_user/:organization' => 'organizations#process_new_user', :as => :organizations_process_user, :via => 'post'
  post 'organizations/invite_user', to: 'organizations#invite_user', as: :org_invite_user
  get 'organizations/private_resources/:id', to: 'organizations#private_resources', as: :org_private_resources
  resources :organizations, path: '/admin/organizations'
  get 'organizations/:id', to: 'organizations#show'
  put 'organizations/deactivate/:id', to: 'organizations#deactivate', as: 'deactivate_organization'
  put 'organizations/reactivate/:id', to: 'organizations#reactivate', as: 'reactivate_organization'
  get 'user_orgs_index', to: 'organizations#user_orgs_index', as: 'user_orgs_index'

  root :to => 'home#index'
  get 'home/error', to: 'home#error', as: :error_page
  get 'tags/:tag', to: 'tags#index', as: :collection_tags
  post 'users/save_subscriptions/:id', to: 'users#save_subscriptions', as: :user_save_subscriptions
  post 'users/remove_subscription/:id', to: 'users#remove_subscription', as: :user_remove_subscription
  get 'users/unlock_user/:id', to: 'users#unlock_user', as: :unlock_user
  get 'users/get_users', to: 'users#get_users', as: :get_users
  get 'users/export', to: 'users#export', as: :users_export
  get 'request_invite', to: 'users#request_invite', as: :request_invite
  post 'users/send_invite', to: 'users#send_invite', as: :send_invite
  devise_for :users, :controllers => {:registrations => 'registrations'}, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users, path: 'admin/users'
  put 'users/deny/:id', to: 'users#deny', as: 'deny_user'
  put 'users/deactivate/:id', to: 'users#deactivate', as: 'deactivate_user'
  put 'users/reactivate/:id', to: 'users#reactivate', as: 'reactivate_user'
  put 'users/remove_membership', to: 'users#remove_membership', as: :remove_membership
  put 'users/update_role', to: 'users#update_role', as: :update_role
  put 'users/remove_cop_membership', to: 'users#remove_cop_membership', as: :remove_cop_membership
  get '/unsubscribe', to: 'users#unsubscribe'


  #HEALTHCHECK
  get '/healthcheck', to: 'healthcheck#check_db'

  # Return 404 for any unmatched paths except those bound for Rails-provided actions
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path !~ %r{^/rails}
  }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource :only => [:edit, :update, :destroy], :find_by => :url
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :rate_collection]
  impressionist :unique => [:impressionable_type, :impressionable_id, :session_hash]

  # GET /collections
  # GET /collections.json
  def index
    redirect_to new_search_path
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    #@page_title = 'View Collection'
    log_view

    # unauthenticated users cannot view private or unnaproved resources
    if @current_user.nil? and (@collection.private || !@collection.approved?)
      redirect_to root_path, alert: 'You do not have access to this private resource.'

      # authenticated users cannot view private resources that arent in their organization unless they are moderators
    elsif !@current_user.nil? and @collection.private and @current_user.has_org(@collection.organization).count == 0 and !can? :approve, @collection
      redirect_to root_path, alert: 'You do not have access to this private resource.'

      # authenticated users cannot view resources that are not approved yet unless they are moderators or are the user that uploaded it
    elsif !@current_user.nil? and !@collection.approved and !can? :approve, @collection and !@current_user == @collection.author
      redirect_to root_path, alert: 'You do not have access to this private resource.'

      # authenticated users that are not mail chimp users should not be able to access newletter only resources
    elsif @collection.newsletter_only and (@current_user.nil? or @current_user.mail_chimp_user == false)
      redirect_to root_path, alert: 'You do not have access to this resource.'
    end

    # check if user should be able to provide feedback
    if !@current_user.nil?
      if @collection.positive_users.include?(current_user.id.to_s) || @collection.negative_users.include?(current_user.id.to_s)
        @show_feedback = false
      else
        @show_feedback = true
      end
    else
      # unauthenticated user so look in their cookies to see if they can provide feedback
      feedback = feedback_array
      if feedback.include?(@collection.id.to_s)
        @show_feedback = false
      else
        @show_feedback = true
      end
    end

    @related_collections = @collection.find_related_tags.limit(5)
    @current_user = current_user

  end

  # GET /collections/new
  def new
    add_crumb("New Collection")
    @page_title = 'New Collection'

    # create new collection and populate
    @collection = Collection.new
    @collection.author_id = current_user.id
    @collection.maintainer_id = current_user.id

    if !params[:organization_id].nil?
      @organization = Organization.find_by :id => params[:organization_id]
      @collection.organization = @organization
    else
      @collection.organization = current_user.organizations.first
    end

    # do some checking to make sure current_user can add collections to
    return authenticate_current_user_role_for_collections
    return authenticate_current_user_for_collection

  end

  # GET /collections/1/edit
  def edit
    add_crumb("Edit Collection")
    @page_title = 'Edit Collection'

    if (cannot? :edit, @collection or !@collection.can_edit(current_user)) and cannot? :moderate, @collection
      redirect_to @collection, alert: 'You cannot edit this collection'
    end

  end

  # POST /collections
  # POST /collections.json
  def create
    add_crumb("New Collection")
    @page_title = 'New Collection'
    @collection = Collection.new(collection_params)
    @collection.organization = Organization.find_by :id => params[:collection][:organization_id]
    @collection.tag_list = params[:collection][:tags]

    # do some authentication to make sure user can edit this collection
    authenticate_current_user_role_for_collections

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collection }
      else
        flash[:error] = "Could not add collection"
        format.html { render action: 'new', status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update

    # do some authentication to make sure user can edit this collection
    authenticate_current_user_role_for_collections

    respond_to do |format|
      @collection.tag_list = params[:collection][:tags]
      if @collection.update(collection_params)
        @collection.save

        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit', status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy

    # do some authentication to make sure user can delete this collection
    authenticate_current_user_role_for_collections

    @collection.destroy
    respond_to do |format|
      flash[:notice] = I18n.t('notices.delete_success')
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  def not_found

  end

  def rate_collection

    if is_number?(params[:positive] )&& is_number?(params[:negative])

      # increment counts
      if @collection.positive.nil?
        @collection.positive = params[:positive]
      else
        @collection.positive = @collection.positive + params[:positive].to_i
      end
      if @collection.negative.nil?
        @collection.negative = params[:negative]
      else
        @collection.negative = @collection.negative + params[:negative].to_i
      end

      if !@current_user.nil?
        # this is an authenticated user, add their ID to the resource as having provided feedback
        if !@collection.positive_users.include?(@current_user.id.to_s) && !@collection.negative_users.include?(@current_user.id.to_s)
          # current user is not in the list so add them to the appropriate array
          if params[:positive].to_i > 0
            puts 'adding to positive'
            new_positive = @collection.positive_users + [@current_user.id]
            @collection.positive_users = new_positive
          elsif params[:negative].to_i > 0
            puts 'adding to negative'
            new_negative = @collection.negative_users + [@current_user.id]
            @collection.negative_users = new_negative
          end
        else
          puts 'already in list'
        end
      else
        puts 'user is not logged in'
      end

      @collection.save!

      # add id of this cookie to the feedback cookie list
      feedback = feedback_array
      if feedback.include?(@collection.id.to_s)
        puts 'do nothing'
      else
        feedback.push(@collection.id)
        save_feedback_cookie(feedback)
      end

    end

    redirect_to @collection, notice: "Your feedback has been recorded"

  end



  private

  def authenticate_current_user_role_for_collections
    if (cannot? :add, @collection or !@collection.can_add_resources(current_user)) and cannot? :moderate, @collection
      redirect_to @collection, alert: 'You cannot edit this collection'
    end
  end

  def authenticate_current_user_for_collection
    if (current_user.organizations.nil? or !current_user.has_approved_org) and cannot? :moderate, @collection
      redirect_to no_approved_orgs_path, alert: 'No approved organizations'
    elsif (@collection.organization.nil? or !@collection.organization.users.exists?(current_user)) and cannot? :moderate, @collection
      redirect_to organizations_path(@collection.organization), alert: 'You are not approved to add collections to this organization'
    end
  end

  def save_feedback_cookie(feedback)
    cookies[:collections_feedback] = (feedback.class == Array) ? feedback.join(",") : ''
  end

  def feedback_array
    cookies[:collections_feedback] ? cookies[:collections_feedback].split(",") : []
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find_by_url(params[:id])
    if @collection.nil?
      redirect_to collections_not_found_path, message: "That collection was not found"
    else
      if @cookies.nil?
        session["init"] = true
      end
      impressionist(@collection)
    end
  end

  def log_view
    Collection.increment_counter(:view_count, @collection.id)
  end

  def is_number? string
    true if Float(string) rescue false
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    params.require(:collection).permit(:activity_id, :url, :title, :description, :status, :author_id, :maintainer_id, :type_id, :organization_id, :license_id, :notes, :tag_list, :image, :private, :newsletter_only)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/collections/_collection.html.erb
<% str_title = ' <i class="bi bi-archive"></i> ' %>
<% str_title = str_title + collection.title.truncate(55) %>
<% if collection.private == true %>
    <% str_title = str_title + ' <i class="fa fa-eye-slash"></i>' %>
<% end %>

<div class="tag-box tag-box-v4 margin-bottom-20 well well-sm">
  <!-- Begin Inner Results -->

  <div class="card border-top-0 border-end-0 border-bottom-0 border-primary border-4">
      <div class="card-body">
      <!-- Begin Inner Results -->
      <% if can? :approve, collection and !collection.approved %>
        <div class="float-end">
          <%= link_to "Approve", approve_submission_path(:submission_id => collection.id, :submission_type => "collection"), :class => "btn btn-outline-primary btn-sm" %></li>
          <%= link_to "Deny", denial_submission_path(:submission_id => collection.id, :submission_type => "collection"), :class => "btn btn-outline-danger btn-sm" %></li>
        </div>
     <% end %>
      <h4 class="card-title pb-2"><%= link_to raw(str_title), collection_path(collection) %></h4>
      <h6 class="card-subtitle mb-2 text-muted">
        <%= raw collection.tags[0..2].map { |t| link_to raw('<span class="badge rounded-pill bg-secondary dark-badge-link"><i class="fa fa-tag"></i> ' + t.name), update_search_path(:tags=>[t.id]) }.join('</span>&nbsp;') %>
        <%= link_to raw('...more'), collection_path(collection) if collection.tag_list.size > 4 %>
      </h6>
      <%= simple_format collection.description.truncate(80) if !collection.description.nil? %>
      <div class="text-muted resource-small"><%= link_to collection.organization.name, organization_path(collection.organization) if !collection.organization.nil? %> (<%= link_to collection.author.name, user_path(collection.author) if !collection.author.nil? %>)</div>
      <div class="row resource-small pt-3">
      <div class="col text-muted fw-light text-center border-end"><%= collection.resources.count %> Resource<% if collection.resources.count > 1 %>s<% end %> in this collection</div>
        <div class="col text-muted fw-light text-center border-end">Uploaded <%= time_ago_in_words collection.created_at %> ago</div>
        <div class="col text-muted fw-light text-center">Last updated <%= time_ago_in_words collection.updated_at %> ago</div>
      </div>
      </div>
    </div>
</div>

app/views/collections/_collection_moderators.html.erb
<% str_title = ' <i class="fa fa-files-o"></i>' %>
<% str_title = str_title + collection.title.truncate(55) %>
<% if collection.private == true %>
    <% str_title = str_title + ' <i class="fa fa-eye-slash"></i>' %>
<% end %>

<div class="tag-box tag-box-v4 margin-bottom-20 well well-sm">
  <!-- Begin Inner Results -->

  <% if can? :approve, collection and !collection.approved %>
      <div class="btn-group pull-right">
        <button type="button" class="btn btn-success"><i class="fa fa-cog"></i></button>
        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-angle-down"></i>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Approve Collection", approve_submission_path(:submission_id => collection.id, :submission_type => "collection") %></li>
          <li class="divider"></li>
          <li><a href="<%= denial_submission_path(:submission_id => collection.id, :submission_type => "collection") %>">Deny Submission</a></li>
        </ul>
      </div>
  <% end %>

  <% if !collection.image.blank? %>
      <p><%= image_tag collection.image.url(:thumb), class: "author pull-left pad-right"  %></p>
  <% end %>
  <h2 class='headline-sm'><% if collection.approved == false %><span class="label label-orange">Pending Approval</span> <% end %><%= link_to raw(str_title), collection_path(collection) %></h2>
  <ul class="list-inline">
    <li>
      <%= raw collection.tag_list[0..2].map { |t| link_to raw('<i class="fa fa-tag"></i> ' + t), update_search_path(:tags=>[t]), class: 'text-highlights rounded' }.join('</li><li>') %>
      <%= link_to raw('...more</li>'), collection_path(collection) if collection.tag_list.size > 4 %>
      <%= raw('</li>') if collection.tag_list.size <= 4 %>

  </ul>
  <p class="text-muted "><smaller>
    <%= simple_format collection.description.truncate(80) if !collection.description.nil? %></smaller>
  </p>
  <ul class="list-inline down-ul">
    <% if collection.resources.count > 0 %>
        <li><%= collection.resources.count %> Resource<% if collection.resources.count > 1 %>s<% end %> in this collection</li>
    <% end %>
    <li>Uploaded <%= time_ago_in_words collection.created_at %> ago</li>
    <li>Last updated <%= time_ago_in_words collection.updated_at %> ago</li>
    <li><%= link_to collection.organization.name, organization_path(collection.organization) if !collection.organization.nil? %> (<%= link_to collection.author.name, user_path(collection.author) if !collection.author.nil? %>)</li>
  </ul>
</div>

app/views/collections/_collection_results.html.erb
<% @collections.each do |collection| %>
    <div class="well well-sm">
      <% if !collection.image.blank? %>
          <p><%= image_tag collection.image.url(:thumb), class: "author pull-left pad-right"  %></p>
      <% end %>
      <%= link_to collection, class: 'btn btn-sm btn-color pull-right' do %>
          <i class="fa fa-eye"></i> View
      <% end %>
      <% str_title = collection.title.truncate(55) %>
      <% if collection.private == true %>
          <% str_title = str_title + ' <i class="fa fa-eye-slash"></i>' %>
      <% end %>
      <%= link_to raw("<h5 class='primary-font'>" + str_title + "</h5>"), collection_path(collection) %>
      <p class="text-muted "><smaller>
        <%= simple_format collection.description.truncate(80) if !collection.description.nil? %></smaller>
      </p>
    </div>
<% end %>

app/views/collections/_facet_org.html.erb
<% if params[:organization_id].present? and Organization.where(id: params[:organization_id]).exists? %>
    <% @organization =  Organization.find(params[:organization_id]) %>
    <%= render partial: 'organizations/info', locals: { :short => true } %>
    <%= link_to url_for(update_search_path(request.parameters.except(:organization_id))), class: 'pull-right' do %>
        <i class="fa fa-times-circle"></i> reset filter
    <% end %>
<% else %>
    <ul class="list-group list-group-flush">
      <% @orgs.each do |o| %>
        <li class="list-group-item available-tags">
          <%= link_to o["name"], update_search_path(request.parameters.merge(:organization_id => o["id"]).except(:page)) %> (<%= o["org_count"] %>) 
        </li>
      <% end %>
    </ul>
<% end %>

app/views/collections/show.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
          <li><%= link_to root_path do %>Home<% end %></li>
          <li><%= link_to (session[:last_search_id] ? search_path(session[:last_search_id]) : new_search_path) do %>Search<% end %></li>
          <li>Collection</li>
      </ol>
    </div>
</section><!-- End Breadcrumbs -->

<!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container">

   <div class="row">
     <div class="col-3 border-end">
      <div class="row border-bottom pb-2 me-1">
        <div class="col fs-5"><i class="bi bi-archive"></i> Collection</div>
        <div class="col d-flex flex-row-reverse available-tags">
          <% if (can? :moderate, @collection) or (@collection.can_edit(@current_user)) or (@collection.can_add_resources(@current_user)) %>
            <div class="dropdown">
              <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-cog"></i>
              </button>
              <ul class="dropdown-menu">
              <% if (can? :moderate, @collection) or @collection.can_edit(current_user) %>
                <li><%= link_to "Edit Collection", edit_collection_path(@collection), class: "dropdown-item" %></li>
              <% end %>
              <% if can? :moderate, @collection or @collection.can_add_resources(@current_user) %>
                <li><%= link_to "Add Resource", new_collection_resourcing_path(@collection), class: "dropdown-item" %></li>
              <% end %>
              <% if can? :delete, @collection or can? :moderate, @collection %>
                <li><%= link_to "Delete", @collection, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "dropdown-item" %></li>
              <% end %>
              <% if can? :approve, @collection and !@collection.approved %>
                <li><%= link_to "Approve collection", approve_submission_path(:submission_id => @collection.id, :submission_type => "collection"), :class => "dropdown-item" %></li>
                <li><%= link_to "Deny Submission", denial_submission_path(:submission_id => @collection.id, :submission_type => "collection"), :class => "dropdown-item" %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
        <ul class="list-group list-group-flush bg-transparent">
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Uploaded By</div>
            <div class="ms-3">
              <%= link_to organization_path(@collection.organization) do %><%= @collection.organization.name %><% end %>
            </div>
          </li>
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Date Added</div>
            <div class="ms-3">
              <%= @collection.created_at.strftime("%Y-%m-%d") %>
            </div>
          </li>
          <% if @related_collections %>
            <li class="list-group-item bg-transparent text-muted">
              <div class="text-danger">Related collections</div>
              <ul class="list-group list-group-flush bg-transparent">
                <% @related_collections.each do |collection| %>
                  <li class="list-group-item bg-transparent"><%= link_to collection do %><%= collection.title %><% end %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
     </div>
     <div class="col-9">
      <div class="border-bottom pb-2"><span class="fs-5"><%= @collection.title %> &nbsp;</span></h5></div>
       <% if @collection.tags.count > 0 %>
        <div class="p-2">
          <% @collection.tags.each do |tag| %>
            <a href="<%= new_search_path(:tags => [tag.id]) %>" class="badge rounded-pill bg-dark dark-badge-link" href="#"><i class="fa fa-tags"></i> <%= tag.name %></a>
          <% end %>
        </div>
       <% end %>
       <div class="card text-bg-light m-2">
        <div class="card-body">
          <%= simple_format @collection.description %>
        </div>
      </div>
      <div class="card m-2">
        <div class="card-body">
          <% if @collection.resources.empty? %>
            <p>
              No resources available in this collection,
              <% if @collection.can_add_resources(current_user) %>
                  <%= link_to 'add some', new_collection_resourcing_path(@collection) if can? :add, @collection and @collection.can_add_resources(current_user) %>
              <% end %>
            </p>
            <% else %>
            <% @collection.resources.order(updated_at: :desc).each do |resource| %>
              <%= render resource %>
              <% if (can? :moderate, @collection) or (@collection.can_edit(@current_user)) or (@collection.can_add_resources(@current_user)) %>
                <div class="d-flex flex-row-reverse"><%= link_to "Remove From Collection", remove_resourcing_path(resource_id: resource.id, collection_id: @collection.id), :data => { :turbo_confirm => 'Are you sure you want to remove this resource? It will not be deleted but will be removed from this collection.' }, class: 'btn btn-outline-danger btn-sm' %></div>
                <div class="border-bottom mb-2">&nbsp; </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>


       
       <div class="mt-2">
        
       </div>
     </div>
   </div>

  </div>
</section><!-- End About Section -->