config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #mount Ckeditor::Engine => '/ckeditor'
  resources :banners
  get 'survey/index'
  get 'survey/done'
  get 'service/index'
  resources :denial_reasons, path: 'admin/denial_reasons'
  get 'moderator/index', to: 'moderator#index', as: :moderate_submissions
  get 'moderator/approve', to: 'moderator#approve', as: :approve_submission
  get 'moderator/denial', to: 'moderator#denial', as: :denial_submission
  post 'moderator/deny', to: 'moderator#deny', as: :deny_submission
  get 'moderator/denied', to: 'moderator#denied', as: :denied_submissions
  get 'moderator/users', to: 'moderator#users', as: :moderator_users

  resources :activities

  get 'resourcings/remove_resourcing', to: 'resourcings#remove_resourcing', as: :remove_resourcing
  resources :resourcings
  get 'resources/log_event', to: 'resources#log_event', as: :log_event
  get 'resources/download', to: 'resources#download', as: :download_resource

  resources :user_types, path: 'admin/user_types'
  resources :organization_types, path: 'admin/organization_types'

  #mount RailsAdmin::Engine => '/cpanel', as: 'rails_admin'

  #resources :batches
  #resources :categories
  resources :tags, path: 'admin/tags'
  get 'tags/guide', to: 'tags#show_guide', as: :show_guide
  resources :tag_types, path: 'admin/tag_types'
  resources :featured_searches
  resources :announcements, path: 'admin/announcements'
  get 'announcements', to: 'announcements#public_announcements', as: :public_announcements
  get 'announcements/:id', to: 'announcements#show_announcement', as: :show_announcement

  resources :cops, path: 'admin/cops'
  get 'cops/:id', to: 'cops#show_cop', as: :show_cop
  get 'cop_event_email_info/:id', to: 'cops#show_event_email_info', as: :cop_event_email_info
  get 'cop_email_info/:id', to: 'cops#show_email_info', as: :cop_email_info
  
  resources :events, path: 'admin/events'
  get 'events', to: 'events#public_events', as: :public_events
  get 'events/:id', to: 'events#show_event', as: :show_event

  get 'faq/index', to: 'faq#index', as: :faq
  resources :users_organizations
  put 'usersorganizations/update_org_role', to: 'users_organizations#update_org_role', as: :update_org_role

  get 'data/csv', to: 'data#csv', as: :data_csv
  #get 'contact', to: 'contact#index', as: :contact
  #get "contact/index"
  get 'about', to: 'about#index', as: :about
  get 'about/types', to: 'about#types', as: :about_resource_types
  get 'about/new_users', to: 'about#new_users', as: :new_users
  get 'about/disclaimer', to: 'about#disclaimer', as: :disclaimer
  get 'about/access_denied', to: 'about#access_denied', as: :access_denied
  get 'about/index'
  get 'admin/index'
  post 'admin/invite_user', to: 'admin#invite_user', as: :invite_user
  get 'admin/contest', to: 'admin#contest', as: :admin_contest
  get 'admin/resource_ratings', to: 'admin#resource_ratings', as: :resource_ratings
  get 'admin/collection_ratings', to: 'admin#collection_ratings', as: :collection_ratings
  get 'admin/survey_report', to: 'admin#survey_report', as: :survey_report
  get 'admin/contest_report', to: 'admin#contest_report', as: :contest_report
  get 'admin/access_report', to: 'admin#access_report', as: :access_report
  #get 'admin/manage_tags', to: 'admin#manage_tags', as: :manage_tags
  #get 'admin/delete_tag', to: 'admin#delete_tag', as: :delete_tag
  #get 'admin/edit_tag', to: 'admin#edit_tag', as: :edit_tag
  #get 'admin/new_tag', to: 'admin#new_tag', as: :new_tag
  #post 'admin/update_tag', to: 'admin#update_tag', as: :update_tag
  get 'admin/orgs', to: 'admin#orgs', as: :orgs
  get 'admin/upload_files', to: 'admin#upload_files', as: :upload_files
  get 'admin/private_resources', to: 'admin#private_resources', as: :private_resources
  get 'admin/pending_submissions', to: 'admin#pending_submissions', as: :pending_submissions
  post 'admin/process_uploaded_files', to: 'admin#process_uploaded_files', as: :process_uploaded_files
  get 'admin/fix_resource_collections_menu', to: 'admin#fix_resource_collections_menu', as: :fix_resource_collections_menu
  get 'admin/fix_resource_collections', to: 'admin#fix_resource_collections', as: :fix_resource_collections

  #get 'ViewerJS', :to => redirect('/ViewerJS/index.html')
  get 'resources/rate_resource', to: 'resources#rate_resource', as: :rate_resource
  get 'resources/not_found', to: 'resources#not_found', as: :resources_not_found
  get 'resources/preview/:id', to: 'resources#preview', as: :resource_preview
  resources :resources

  get 'searches/update_search', to: 'searches#update_search', as: :update_search
  resources :searches

  get 'collections/not_found', to: 'collections#not_found', as: :collections_not_found
  get 'collections/rate_collection', to: 'collections#rate_collection', as: :rate_collection
  resources :collections do
    resources :resourcings
  end
  get 'about/no_approved_org', to: 'about#no_approved_org', as: :no_approved_orgs

  resources :types

  resources :licenses

  get 'organizations/not_found', to: 'organizations#not_found', as: :organization_not_found
  get 'organizations/add_user/:organization', to: 'organizations#add_user', as: :organization_add_user
  get 'organizations/apply', to: 'organizations#apply', as: :organization_apply
  get 'organizations/edit_user/:userorg', to: 'organizations#edit_user', as: :users_organizations_edit_role
  get 'organizations/approve_organization/:organization', to: 'organizations#approve_organization', as: :organization_approve
  get 'organizations/process_application', to: 'organizations#process_application', as: :organization_process_application
  match 'organizations/process_application_denial' => 'organizations#process_application_denial', :as => :organizations_process_application_denial, :via => 'post'
  match 'organizations/add_user/:organization' => 'organizations#process_new_user', :as => :organizations_process_user, :via => 'post'
  post 'organizations/invite_user', to: 'organizations#invite_user', as: :org_invite_user
  get 'organizations/private_resources/:id', to: 'organizations#private_resources', as: :org_private_resources
  resources :organizations, path: '/admin/organizations'
  get 'organizations/:id', to: 'organizations#show'
  put 'organizations/deactivate/:id', to: 'organizations#deactivate', as: 'deactivate_organization'
  put 'organizations/reactivate/:id', to: 'organizations#reactivate', as: 'reactivate_organization'
  get 'user_orgs_index', to: 'organizations#user_orgs_index', as: 'user_orgs_index'

  root :to => 'home#index'
  get 'home/error', to: 'home#error', as: :error_page
  get 'tags/:tag', to: 'tags#index', as: :collection_tags
  post 'users/save_subscriptions/:id', to: 'users#save_subscriptions', as: :user_save_subscriptions
  post 'users/remove_subscription/:id', to: 'users#remove_subscription', as: :user_remove_subscription
  get 'users/unlock_user/:id', to: 'users#unlock_user', as: :unlock_user
  get 'users/get_users', to: 'users#get_users', as: :get_users
  get 'users/export', to: 'users#export', as: :users_export
  get 'request_invite', to: 'users#request_invite', as: :request_invite
  post 'users/send_invite', to: 'users#send_invite', as: :send_invite
  devise_for :users, :controllers => {:registrations => 'registrations'}, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users, path: 'admin/users'
  put 'users/deny/:id', to: 'users#deny', as: 'deny_user'
  put 'users/deactivate/:id', to: 'users#deactivate', as: 'deactivate_user'
  put 'users/reactivate/:id', to: 'users#reactivate', as: 'reactivate_user'
  put 'users/remove_membership', to: 'users#remove_membership', as: :remove_membership
  put 'users/update_role', to: 'users#update_role', as: :update_role
  put 'users/remove_cop_membership', to: 'users#remove_cop_membership', as: :remove_cop_membership
  get '/unsubscribe', to: 'users#unsubscribe'


  #HEALTHCHECK
  get '/healthcheck', to: 'healthcheck#check_db'

  # Return 404 for any unmatched paths except those bound for Rails-provided actions
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path !~ %r{^/rails}
  }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @featured_searches = FeaturedSearch.home_searches.order(:name)
    @announcements = Announcement.active.is_public.featured.limit(5)
    @events = Event.active.is_public.featured.limit(5)
  end

  def error
    @page_title = 'Something went wrong'
  end
end

app/views/home/_announcements.html.erb
<div class="hero-box border-success card" data-intro="Check this announcements box to stay up to date. Click on an individual announcement to see details, or click 'more' to view all recent announcements.">
  <div class="card-body">
    <h3 class="card-title text-success">Announcements</h3>
    <div class="scrollable">
      <div class="row ps-2 pe-2 text-secondary card-text">
        <% @announcements.each do |a| %>
          <div class="border-bottom p-2">
            <span class="text-danger"><%= link_to a.name, show_announcement_path(a), data: { turbo_frame: "modal" } %></span><br>
            <small>posted <%= a.created_at.strftime("%Y-%m-%d") %></small>
          </div>
        <% end %>
      </div>
    </div>

    <div class="pt-2 card-link  d-flex flex-row-reverse">
      <%= link_to raw('more  &raquo;'), public_announcements_path %> 
    </div>
  </div>
</div>

app/views/home/_cops.html.erb
<% if !user_signed_in? %>
  <h3 class="card-title text-success">Register</h3>
  <div class="row p-2 d-flex text-secondary">
    Contribute to the Jordan KaMP! Click the envelope to request an invitation.
  </div>
  <div class="col d-flex justify-content-center">
    <%= link_to request_invite_path do %><i class="bi bi-envelope"></i><% end %>
  </div>

<%  elsif user_signed_in? %>
  <h3 class="card-title text-success">Communities of Practice</h3>
  <div class="scrollable">
    <div class="row p-2 d-flex text-secondary card-text">
      <ul class="list-group list-group-flush bg-transparent">
        <% Cop.order(:name).each do |cop| %>
          <% if current_user.cops.include?(cop) %>
            <li class="list-group-item bg-transparent"><%= link_to cop.name, show_cop_path(cop) %></li>
          <% else %>
            <li class="list-group-item bg-transparent"><%= cop.name %> <a class="btn btn-sm btn-outline-primary float-end" href="mailto:<%=cop.admin.email%>?subject=Jordan KAMP: Request to Join COP&body=Dear Admin,%0D%0A KAMP user <%= current_user.name %> (<%=current_user.email %>) would like to join the Community of Practice <%= cop.name %>. Please review their request and admit them if you approve.%0D%0A Regards,%0D%0AJordan KAMP">Join</a></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <h3 class="card-title text-success">FAQ</h3>
  <div class="scrollable">
    <div class="d-flex text-secondary card-text">
      Welcome to the Jordan KAMP, a place where development resources can be shared with the Jordan M&E community. Anyone can view resources, but registration is required to submit. Please click “More” to learn about the KAMP.
    </div>
  </div>
  <div class="pt-2 d-flex flex-row-reverse">
    <%= link_to raw('more  &raquo;'), faq_path %> 
  </div>
<% end %>

app/views/home/_events.html.erb
<div class="hero-box border-success card" data-intro="Look for upcoming events here. Click on an individual event to see details like time, mode, and location; or click 'more' to view all events.">
  <div class="card-body">
    <h3 class="card-title text-success">Events</h3>
    <div class="scrollable">
    <div class="row ps-2 pe-2 d-flex text-secondary card-text">
      <% @events.each do |e| %>
        <div class="border-bottom p-2">
          <span class="text-danger"><%= link_to e.name, show_event_path(e), data: { turbo_frame: "modal" } %></span><br>
          <small>event date <%= e.start_date.strftime("%Y-%m-%d") %></small>
        </div>
      <% end %>
      
    </div>
    </div>
    <div class="pt-2 d-flex flex-row-reverse">
      <%= link_to raw('more  &raquo;'), public_events_path %> 
    </div>
  </div>
</div>

app/views/home/error.html.erb
<% content_for :title do %><%= @page_title %><% end %>
<!--=== Content Part ===-->
<div class="container content">
  <!-- About Description -->
  <div class="row">
    <div class="col-xs-12">

    </div>
  </div>
</div>

app/views/home/index.html.erb
  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel">

        <div class="carousel-inner" role="listbox">


          <!-- Slide 2 -->
          <div class="carousel-item active" style="background-image: url(/img/amman_bg_2.jpg)">
            <div class="carousel-container">
              <div class="carousel-content">
              <div class="row">
                <div class="col-md-4 pt-3">
                  <div class="card card-body border-0 home-about-box">
                    <h2>Welcome to the <span>Jordan Knowledge Management Portal</span></h2>
                  
                    <div class="ps-5 pb-2">
                      This portal is a repository of development resources designed to improve sharing of data and information between the USAID/Jordan Mission, local implementing partners and development organizations within Jordan.
                      <br/> <%= link_to raw('Read more  &raquo;'), about_index_path %> 
                      &nbsp; &nbsp; <a href="https://www.youtube.com/embed/EwYX-O1HZHQ?si=qQ6plfbIJAol72hi" target="_blank">View introductory video  &raquo;</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-8 align-middle">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="hero-box border-danger card">
                        <div class="card-body">
                          <h3 class="card-title text-danger pb-3">Find Resources</h3>
                          <p class="card-text">
                            <% if @search.nil? %>
                                <%  search = Search.new %>
                            <% else %>
                                <% search = @search %>
                            <% end %>
                            <div data-intro="Use this to box to search for resources and collections from the KaMP home page. Beneath the search bar, note the number of resources and collections uploaded to this repository, which is constantly increasing.">
                              <%= render partial: 'searches/form', locals: { search: search } %>
                            </div>
                            <div class="row pt-4 d-flex align-items-center text-secondary">
                              <div class="col d-flex justify-content-center">
                                <%= Resource.all.count %> Resources
                              </div>
                              <div class="col d-flex justify-content-center text-secondary">
                                <%= Collection.all.count %> Collections
                              </div>
                            </div>
                          </p>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="hero-box border-success card" <% if !user_signed_in? %>
                        data-intro="Register for a free account here. You can access all public resources and collections without having an account on the KaMP, but to join an organization or a Community of Practice, or contribute resources to the KaMP repository, you will need to create an account. Click the envelope to begin the simple registration process."
                        <% end %>
                      >
                        <div class="card-body">
                          <%= render  'cops' %>
                        </div>
                      </div>
                    </div>
                  </div>
                   <div class="row">
                    <div class="col-lg-6">
                      <% if @announcements.length != 0 %>
                        <%= render  'announcements' %>
                      <% end %>
                    </div>
                    <div class="col-lg-6">
                      <% if @events.length != 0 %>
                        <%= render  'events' %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Featured Section ======= -->
    <section id="featured" class="featured">
      <div class="container" data-intro="Click on a topic to be taken to a list of relevant resources and collections.">

        <div class="row">
          <% @featured_searches.each do |fs| %>
            <div class="col-lg-3 pb-3">
              <div class="icon-box">
                <h3><a href="<%= fs.get_url %>">
                  <i class="<%= fs.icon_identifier %>"></i>
                  Learn About <br/>
                  <%= fs.name %>
                </a>
              </h3>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </section><!-- End Featured Section -->

    <section id="about" class="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
              <iframe width="100%" height="500px" src="https://www.youtube.com/embed/EwYX-O1HZHQ?si=qQ6plfbIJAol72hi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </div>
          <div class="col-lg-6">
            <p>USAID/Jordan created the Jordan Development KaMP – a web-based repository of development information resources designed to improve sharing of data and information between the USAID/Jordan Mission, local implementing partners and development organizations within Jordan.</p>
            <p>The KaMP will be available to all interested development partners in Jordan and is populated with resources identified and uploaded by staff from USAID/Jordan, MESP, Implementing Partners and other portal users.</p>
            <p> <%= link_to raw('Read more  &raquo;'), about_index_path %> </p>

          </div>
        </div>
      </div>
    </section>
    


  </main><!-- End #main -->