config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #mount Ckeditor::Engine => '/ckeditor'
  resources :banners
  get 'survey/index'
  get 'survey/done'
  get 'service/index'
  resources :denial_reasons, path: 'admin/denial_reasons'
  get 'moderator/index', to: 'moderator#index', as: :moderate_submissions
  get 'moderator/approve', to: 'moderator#approve', as: :approve_submission
  get 'moderator/denial', to: 'moderator#denial', as: :denial_submission
  post 'moderator/deny', to: 'moderator#deny', as: :deny_submission
  get 'moderator/denied', to: 'moderator#denied', as: :denied_submissions
  get 'moderator/users', to: 'moderator#users', as: :moderator_users

  resources :activities

  get 'resourcings/remove_resourcing', to: 'resourcings#remove_resourcing', as: :remove_resourcing
  resources :resourcings
  get 'resources/log_event', to: 'resources#log_event', as: :log_event
  get 'resources/download', to: 'resources#download', as: :download_resource

  resources :user_types, path: 'admin/user_types'
  resources :organization_types, path: 'admin/organization_types'

  #mount RailsAdmin::Engine => '/cpanel', as: 'rails_admin'

  #resources :batches
  #resources :categories
  resources :tags, path: 'admin/tags'
  get 'tags/guide', to: 'tags#show_guide', as: :show_guide
  resources :tag_types, path: 'admin/tag_types'
  resources :featured_searches
  resources :announcements, path: 'admin/announcements'
  get 'announcements', to: 'announcements#public_announcements', as: :public_announcements
  get 'announcements/:id', to: 'announcements#show_announcement', as: :show_announcement

  resources :cops, path: 'admin/cops'
  get 'cops/:id', to: 'cops#show_cop', as: :show_cop
  get 'cop_event_email_info/:id', to: 'cops#show_event_email_info', as: :cop_event_email_info
  get 'cop_email_info/:id', to: 'cops#show_email_info', as: :cop_email_info
  
  resources :events, path: 'admin/events'
  get 'events', to: 'events#public_events', as: :public_events
  get 'events/:id', to: 'events#show_event', as: :show_event

  get 'faq/index', to: 'faq#index', as: :faq
  resources :users_organizations
  put 'usersorganizations/update_org_role', to: 'users_organizations#update_org_role', as: :update_org_role

  get 'data/csv', to: 'data#csv', as: :data_csv
  #get 'contact', to: 'contact#index', as: :contact
  #get "contact/index"
  get 'about', to: 'about#index', as: :about
  get 'about/types', to: 'about#types', as: :about_resource_types
  get 'about/new_users', to: 'about#new_users', as: :new_users
  get 'about/disclaimer', to: 'about#disclaimer', as: :disclaimer
  get 'about/access_denied', to: 'about#access_denied', as: :access_denied
  get 'about/index'
  get 'admin/index'
  post 'admin/invite_user', to: 'admin#invite_user', as: :invite_user
  get 'admin/contest', to: 'admin#contest', as: :admin_contest
  get 'admin/resource_ratings', to: 'admin#resource_ratings', as: :resource_ratings
  get 'admin/collection_ratings', to: 'admin#collection_ratings', as: :collection_ratings
  get 'admin/survey_report', to: 'admin#survey_report', as: :survey_report
  get 'admin/contest_report', to: 'admin#contest_report', as: :contest_report
  get 'admin/access_report', to: 'admin#access_report', as: :access_report
  #get 'admin/manage_tags', to: 'admin#manage_tags', as: :manage_tags
  #get 'admin/delete_tag', to: 'admin#delete_tag', as: :delete_tag
  #get 'admin/edit_tag', to: 'admin#edit_tag', as: :edit_tag
  #get 'admin/new_tag', to: 'admin#new_tag', as: :new_tag
  #post 'admin/update_tag', to: 'admin#update_tag', as: :update_tag
  get 'admin/orgs', to: 'admin#orgs', as: :orgs
  get 'admin/upload_files', to: 'admin#upload_files', as: :upload_files
  get 'admin/private_resources', to: 'admin#private_resources', as: :private_resources
  get 'admin/pending_submissions', to: 'admin#pending_submissions', as: :pending_submissions
  post 'admin/process_uploaded_files', to: 'admin#process_uploaded_files', as: :process_uploaded_files
  get 'admin/fix_resource_collections_menu', to: 'admin#fix_resource_collections_menu', as: :fix_resource_collections_menu
  get 'admin/fix_resource_collections', to: 'admin#fix_resource_collections', as: :fix_resource_collections

  #get 'ViewerJS', :to => redirect('/ViewerJS/index.html')
  get 'resources/rate_resource', to: 'resources#rate_resource', as: :rate_resource
  get 'resources/not_found', to: 'resources#not_found', as: :resources_not_found
  get 'resources/preview/:id', to: 'resources#preview', as: :resource_preview
  resources :resources

  get 'searches/update_search', to: 'searches#update_search', as: :update_search
  resources :searches

  get 'collections/not_found', to: 'collections#not_found', as: :collections_not_found
  get 'collections/rate_collection', to: 'collections#rate_collection', as: :rate_collection
  resources :collections do
    resources :resourcings
  end
  get 'about/no_approved_org', to: 'about#no_approved_org', as: :no_approved_orgs

  resources :types

  resources :licenses

  get 'organizations/not_found', to: 'organizations#not_found', as: :organization_not_found
  get 'organizations/add_user/:organization', to: 'organizations#add_user', as: :organization_add_user
  get 'organizations/apply', to: 'organizations#apply', as: :organization_apply
  get 'organizations/edit_user/:userorg', to: 'organizations#edit_user', as: :users_organizations_edit_role
  get 'organizations/approve_organization/:organization', to: 'organizations#approve_organization', as: :organization_approve
  get 'organizations/process_application', to: 'organizations#process_application', as: :organization_process_application
  match 'organizations/process_application_denial' => 'organizations#process_application_denial', :as => :organizations_process_application_denial, :via => 'post'
  match 'organizations/add_user/:organization' => 'organizations#process_new_user', :as => :organizations_process_user, :via => 'post'
  post 'organizations/invite_user', to: 'organizations#invite_user', as: :org_invite_user
  get 'organizations/private_resources/:id', to: 'organizations#private_resources', as: :org_private_resources
  resources :organizations, path: '/admin/organizations'
  get 'organizations/:id', to: 'organizations#show'
  put 'organizations/deactivate/:id', to: 'organizations#deactivate', as: 'deactivate_organization'
  put 'organizations/reactivate/:id', to: 'organizations#reactivate', as: 'reactivate_organization'
  get 'user_orgs_index', to: 'organizations#user_orgs_index', as: 'user_orgs_index'

  root :to => 'home#index'
  get 'home/error', to: 'home#error', as: :error_page
  get 'tags/:tag', to: 'tags#index', as: :collection_tags
  post 'users/save_subscriptions/:id', to: 'users#save_subscriptions', as: :user_save_subscriptions
  post 'users/remove_subscription/:id', to: 'users#remove_subscription', as: :user_remove_subscription
  get 'users/unlock_user/:id', to: 'users#unlock_user', as: :unlock_user
  get 'users/get_users', to: 'users#get_users', as: :get_users
  get 'users/export', to: 'users#export', as: :users_export
  get 'request_invite', to: 'users#request_invite', as: :request_invite
  post 'users/send_invite', to: 'users#send_invite', as: :send_invite
  devise_for :users, :controllers => {:registrations => 'registrations'}, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users, path: 'admin/users'
  put 'users/deny/:id', to: 'users#deny', as: 'deny_user'
  put 'users/deactivate/:id', to: 'users#deactivate', as: 'deactivate_user'
  put 'users/reactivate/:id', to: 'users#reactivate', as: 'reactivate_user'
  put 'users/remove_membership', to: 'users#remove_membership', as: :remove_membership
  put 'users/update_role', to: 'users#update_role', as: :update_role
  put 'users/remove_cop_membership', to: 'users#remove_cop_membership', as: :remove_cop_membership
  get '/unsubscribe', to: 'users#unsubscribe'


  #HEALTHCHECK
  get '/healthcheck', to: 'healthcheck#check_db'

  # Return 404 for any unmatched paths except those bound for Rails-provided actions
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path !~ %r{^/rails}
  }
end

app/views/resources/_guidance.html.erb
<div class="card text-bg-light mb-2">
  <div class="card-body">
    <h5 class="card-title text-dark fs-6">Resource Name</h5>
    <p class="card-text resource-small text-dark">The resource name should be short but descriptive, as this is the most immediate way others will be able to identify the resource in the portal. The resource name can be a great opportunity to include some key words as well.</p>
    <h6 class="card-subtitle mb-2 text-body-secondary resource-small">Example: Mid-Term Evaluation of the Jordan health care initiative</h6>
  </div>
</div>

<div class="card text-bg-light mb-2">
  <div class="card-body">
    <h5 class="card-title text-dark fs-6">File/Source URL</h5>
    <p class="card-text resource-small text-dark">You may either upload a resource file or link to an external resource. If linking to an external resource, the Source URL is required. If uploading a resource file, you may optionally provide the Source URL for that resource, where applicable.</p>
  </div>
</div>

<div class="card text-bg-light mb-2">
  <div class="card-body">
    <h5 class="card-title text-dark fs-6">Tags</h5>
    <p class="card-text resource-small text-dark">You can use as many sector/topic tags as needed. If you don't find a tag, you can combine a few high-level tags to ensure all key words are included (Example: "Monitoring and Evaluation" -> #monitoring #evaluation). The portal will not have ALL possible tags so be sure to include in the notes, resource name, or description any other key words for which there are no matching system tags.</p>
    <h6 class="card-subtitle mb-2 text-body-secondary resource-small">Example: If the report is on counter trafficking of youth in a conflict zone you could select these tags: #youth, #conflict #trafficking #democracyandgovernance</h6>
    <p class="card-text resource-small font-weight-bold"><%= link_to 'Index of Available Tags', show_guide_path, data: { turbo_frame: "modal"} %></p>
  </div>
</div>

<div class="card text-bg-light mb-2">
  <div class="card-body">
    <h5 class="card-title text-dark fs-6">Description</h5>
    <p class="card-text resource-small text-dark">Please keep this section clean and concise. Answer these questions when you write it: What is this resource about? How was it used? How can this resource be useful to others?</p>
  </div>
</div>

app/views/resources/_resource_details_column.html.erb
<% if resource.can_edit(@current_user) %>
    <div class="headline"><h4>Manage Resource</h4></div>
    <ul class="list-group sidebar-nav-v1">
      <% if resource.can_edit(current_user) %>
          <li class="list-group-item"><%= link_to edit_resource_path(resource), class: 'btn btn-rounded btn-primary' do %><i class="fa fa-edit"></i> Edit Resource<% end %></li>
      <% end %>
      <% if can? :delete, resource or can? :moderate, resource %>
          <li class="list-group-item"><%= link_to resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-rounded btn-primary' do %><i class="fa fa-remove"></i> Delete<% end %></li>
      <% end %>
    </ul>
<% end %>
<% if can? :approve, @resource and !@resource.approved %>
    <ul class="list-group sidebar-nav-v1">
      <li class="list-group-item"><%= link_to approve_submission_path(submission_id: @resource.id, submission_type: "resource"), data: { confirm: 'Are you sure you want to approve this resource?' }, class: "btn btn-rounded btn-primary" do %><i class="fa fa-thumbs-up"></i> Approve Resource<% end %></li>
      <li class="list-group-item"><%= link_to denial_submission_path(submission_id: @resource.id, submission_type: "resource"), class: "btn btn-rounded btn-primary" do %><i class="fa fa-thumbs-down"></i> Deny Resource<% end %></li>
    </ul>
    <br>
<% end %>

<div class="well well-sm">
  <% if !resource.issue_date.blank? %>
      <p><strong>Date Added</strong><br>
        <%= resource.created_at.strftime("%Y-%m-%d") %></p>
  <% end %>
  <% if !resource.corporate_authorship.blank? %>
      <p><strong>Corporate Authorship</strong><br><%= resource.corporate_authorship %></p>
  <% end %>
  <% if !resource.issue_date.blank? %>
      <p><strong>Issue Date</strong><br>
        <%= resource.issue_date %></p>
  <% end %>
  <p><strong>Uploaded By:</strong><br>
    <% if !resource.organization.nil? %>
        <%= link_to organization_path(resource.organization) do %>
            <% if resource.organization.logo.blank? %>
                <img src="/img/placeholder-organization.png" alt="Placeholder Image" style="height: 20px; width: 50px;" class="img-responsive pull-left pad-right">
                <%= resource.organization.name %>
            <% else %>
                <img src="<%= resource.organization.logo.expiring_url(10) %>" alt="<%= resource.organization.name %>" style="height: 20px; width: 50px;" class="img-responsive pull-left pad-right">
                <%= resource.organization.name %>
            <% end %>
        <% end %>
    <% end %>
    <br>
    (<%= link_to resource.author.name, user_path(resource.author) if !resource.author.nil? %>)

    <% if can? :manage, :all and !resource.batch.nil?  %>
        <br><small><strong>Batch:</strong> <%= link_to resource.batch.name, batch_path(resource.batch) %></small><br>
    <% end %>
  </p>
  <p><strong>Resource Type</strong><br>
    <%= resource.resource_type %></p>

  <% if !resource.language.blank? %>
      <p><strong>Language</strong><br>
        <%= resource.language.titlecase %></p>
  <% end %>
  <% if !resource.activity_id.nil? %>
      <p><strong>Activity</strong><br>
        <%= resource.activity.name %></p>
  <% end %>
</div>

<% if resource.collections.count > 0 %>
    <div class="headline"><h4>Collections</h4></div>
    <p><small>This resource is part of the following collections:</small></p>
    <ul class="list-group sidebar-nav-v1" id="sidebar-nav">
      <% resource.collections.each do |collection| %>
      <li class="list-group-item">
        <%= link_to collection do %><%= collection.title.truncate(50) %><% end %>
      </li>
      <% end %>
    </ul>
<% end %>



<% if resource.private %>
    <div class="panel panel-green">
      <div class="panel-heading"><i class="fa fa-eye-slash"></i> Private Resource</div>
      <div class="panel-body">
        This resource is marked <b>private</b> so can only be viewed by members of your organization.
      </div>
    </div>
<% end %>

app/views/resources/_resource_moderators.html.erb
<% str_title = resource.name.truncate(55) %>
<% if resource.private == true %>
<% str_title = str_title + ' <i class="fa fa-lock"></i>' %>
<% end %>
<% header_text = ' <i class="fa fa-file"></i>' %>
<%
header_text = header_text + str_title

if resource.private == 1
header_text = header_text + " <i class='fa fa-lock'></i>"
end

header_text = header_text + ""
%>
<div class="tag-box tag-box-v2 margin-bottom-20 well well-sm">
    <!-- Begin Inner Results -->
    <% if can? :approve, resource and resource.approved != true %>
    <div class="pull-right">
        <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-cog"></i>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Approve Resource", approve_submission_path(:submission_id => resource.id, :submission_type => "resource", :class => "dropdown-item") %></li>
          <li><a class="dropdown-item" href="<%= denial_submission_path(:submission_id => resource.id, :submission_type => "resource") %>">Deny Submission</a></li>
        </ul>
        </div>
    </div>
    <% end %>
    <h2 class='headline-sm'><% if resource.approved == false %><span class="label label-orange">Pending Approval</span> <% end %><%= link_to raw(header_text), resource_path(resource) %></h2>
    <% if !resource.collection.nil? %>
    <ul class="list-inline up-ul">
        <li><i class="fa fa-files-o" rel="tooltip" title="This Resource is part of a Collection"></i> <%= link_to resource.collection.title, collection_path(resource.collection) %></li>
    </ul>
    <% end %>
    <ul class="list-inline">
        <li><%= resource.resource_type %></li>
        <li>
            <%= raw('<span class="text-muted"><i class="fa fa-language"></i> English</span>') if resource.language == 'english' %>
            <%= raw('<span class="text-muted"><i class="fa fa-language"></i> Arabic</span>') if resource.language == 'arabic' %>

        </li>
        <li>
            <%= raw resource.tag_list[0..2].map { |t| link_to raw('<i class="fa fa-tag"></i> ' + t), update_search_path(:tags=>[t]), class: 'text-highlights rounded' }.join('</li><li>') %>
        <%= link_to raw('...more</li>'), resource_path(resource) if resource.tag_list.size > 4 %>
        <%= raw('</li>') if resource.tag_list.size <= 4 %>

    </ul>
    <%= simple_format resource.description.truncate(200) %>
    <ul class="list-inline down-ul">
        <% if resource.collections.count > 0 %>
        <li>Used by <%= resource.collections.count %> Collection<% if resource.collections.count > 1 %>s<% end %></li>
        <% end %>
        <% if !resource.issue_date.nil? and !resource.issue_date.blank? %>
        <li>Issued on <%= resource.issue_date %>.</li>
        <% end %>
        <li>Uploaded <%= time_ago_in_words resource.created_at %> ago</li>
        <li>Last updated <%= time_ago_in_words resource.updated_at %> ago</li>
        <li><%= link_to resource.organization.name, organization_path(resource.organization) if !resource.organization.nil? %> (<%= link_to resource.author.name, user_path(resource.author) if !resource.author.nil? %>)</li>
    </ul>
</div>

app/views/resources/_resource_results.html.erb
 <% if !resource.private || resource.organization.can_add_collections(current_user) %>
    <% str_title = resource.name.truncate(55) %>
    <% if resource.private == true %>
        <% str_title = str_title + ' <i class="fa fa-lock"></i>' %>
    <% end %>
     <%
        header_text = "" + str_title

        if resource.private == 1
          header_text = header_text + " <i class='fa fa-lock'></i>"
        end

        header_text = header_text + ""
     %>
     <div class="tag-box tag-box-v2 margin-bottom-20 well well-sm">
           <!-- Begin Inner Results -->
       <h2 class='headline-sm'><%= link_to raw(header_text), resource_path(resource) %></h2>
       <% if !resource.collection.nil? %>
           <ul class="list-inline up-ul">
             <li><i class="fa fa-files-o" rel="tooltip" title="This Resource is part of a Collection"></i> <%= link_to resource.collection.title, collection_path(resource.collection) %></li>
           </ul>
       <% end %>
       <ul class="list-inline">
         <li><%= resource.resource_type %></li>
         <li>
           <%= raw('<span class="text-muted"><i class="fa fa-language"></i> English</span>') if resource.language == 'english' %>
           <%= raw('<span class="text-muted"><i class="fa fa-language"></i> Arabic</span>') if resource.language == 'arabic' %>

         </li>
         <li>
           <%= raw resource.tag_list[0..2].map { |t| link_to raw('<i class="fa fa-tag"></i> ' + t), update_search_path(:tags=>[t]), class: 'text-highlights rounded' }.join('</li><li>') %>
           <%= link_to raw('...more</li>'), resource_path(resource) if resource.tag_list.size > 4 %>
           <%= raw('</li>') if resource.tag_list.size <= 4 %>

       </ul>
       <%= simple_format resource.description.truncate(200) %>
       <ul class="list-inline down-ul">
         <% if resource.collections.count > 0 %>
         <li><%= resource.collections.count %> Collection<% if resource.collections.count > 1 %>s<% end %></li>
         <% end %>
        <% if !resource.issue_date.nil? and !resource.issue_date.blank? %>
             <li>Issued on <%= resource.issue_date %>.</li>
           <% end %>
         <li>Uploaded <%= time_ago_in_words resource.created_at %> ago</li>
         <li><%= link_to resource.organization.name, organization_path(resource.organization) if !resource.organization.nil? %> (<%= link_to resource.author.name, user_path(resource.author) if !resource.author.nil? %>)</li>
       </ul>
     </div>

 <% end %>

app/views/resources/download.html.erb
<p class="ml-20">
  Sorry, there was an error accessing this resource. Please contact us at help@decentdata.world
</p>

app/views/resources/edit.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
          <li><%= link_to root_path do %>Home<% end %></li>
          <li><%= link_to (session[:last_search_id] ? search_path(session[:last_search_id]) : new_search_path) do %>Search<% end %></li>
          <li>Edit Resource</li>
      </ol>
    </div>
</section><!-- End Breadcrumbs -->


<!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container">
    <div class="row">
    <div class="col-3 border-end">
      <h5 class="border-bottom pb-2">Guidance</h5>
      <%= render 'guidance' %>
      <br/>
    </div>
    <div class="col-9">
      <div class="h5 border-bottom pb-2">Edit Resource</div>
      <%= render partial: 'form', locals: { resource: @resource, destination: '' } %>
    </div>
  </div>
</section>

  

app/views/resources/log_event.html.erb
logged

app/views/resources/not_found.html.erb
<!--=== Content Part ===-->
<div class="container content">
  <div class="row">
      <div class="tag-box tag-box-v3 form-page">
        The resource you are trying to view was not found. <%= link_to "Try searching for something else?", new_search_path %>

      </div>
  </div>
</div>

app/views/resources/show.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
          <li><%= link_to root_path do %>Home<% end %></li>
          <li><%= link_to (session[:last_search_id] ? search_path(session[:last_search_id]) : new_search_path) do %>Search<% end %></li>
          <li>Resource</li>
      </ol>
    </div>
</section><!-- End Breadcrumbs -->

<!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container">

   <div class="row">
     <div class="col-3 border-end">
      <div class="row border-bottom pb-2 me-1">
        <div class="col fs-5"><i class="bi bi-file-earmark"></i> Resource</div>
        <div class="col d-flex flex-row-reverse available-tags">
          <% if @resource.can_edit(@current_user) || (can? :approve, @resource and @resource.approved != true) %>
            <div class="dropdown">
              <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-cog"></i>
              </button>
              <ul class="dropdown-menu">
              <% if @resource.can_edit(current_user) %>
                <li><%= link_to "Edit Resource", edit_resource_path(@resource), class: "dropdown-item" %></li>
              <% end %>
              <% if can? :delete, @resource || (@resource.organization && @resource.organization.can_edit_organization(current_user)) %>
                  <li><%= link_to "Delete", @resource, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "dropdown-item" %></li>
              <% end %>
              <% if (can? :approve, @resource || (@resource.organization && @resource.organization.can_edit_organization(current_user))) && !@resource.approved %>
                <li><%= link_to "Approve Resource", approve_submission_path(:submission_id => @resource.id, :submission_type => "resource"), :class => "dropdown-item" %></li>
                <li><%= link_to "Deny Submission", denial_submission_path(:submission_id => @resource.id, :submission_type => "resource"), :class => "dropdown-item" %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
        <ul class="list-group list-group-flush bg-transparent">
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Language</div>
            <div class="ms-3"><%= @resource.language.titlecase %></div>
          </li>
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Resource Type</div>
            <div class="ms-3">
              <%= @resource.resource_type %>
            </div>
          </li>
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Uploaded By</div>
            <div class="ms-3">
              <% if @resource.organization %> <%= link_to organization_path(@resource.organization) do %><%= @resource.organization.name %><% end %> <% end %>
            </div>
          </li>
          <li class="list-group-item bg-transparent text-muted">
            <div class="text-danger">Date Added</div>
            <div class="ms-3">
              <%= @resource.created_at.strftime("%Y-%m-%d") %>
            </div>
          </li>
          <% if @resource.corporate_authorship && @resource.corporate_authorship.length > 0 %>
            <li class="list-group-item bg-transparent text-muted">
              <div class="text-danger">Corporate Authorship</div>
              <div class="ms-3">
                <%= @resource.corporate_authorship %>
              </div>
            </li>
          <% end %>
          <% if @resource.collections.count > 0 %>
            <li class="list-group-item bg-transparent text-muted">
              <div class="text-danger">Collections</div>
              <ul class="list-group list-group-flush bg-transparent">
                <% @resource.collections.each do |collection| %>
                  <li class="list-group-item bg-transparent "><%= link_to collection do %><%= collection.title %><% end %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
          <% if @related_resources %>
            <li class="list-group-item bg-transparent text-muted">
              <div class="text-danger">Related Resources</div>
              <ul class="list-group list-group-flush bg-transparent">
                <% @related_resources.each do |resource| %>
                  <li class="list-group-item bg-transparent"><%= link_to resource do %><%= resource.name %><% end %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
     </div>
     <div class="col-9">
      <div class="border-bottom pb-2"><span class="fs-5"><%= @resource.name %> &nbsp;</span></div>
      <div class="border-bottom fw-light bg-light bg-gradient p-2 pt-3">
        <% if !@resource.attachment.blank? %>
          <h6><%= link_to download_resource_path(:id => @resource.url), title: "Filename of resource", target: "_blank" do %><i class="bi bi-download"></i> <%= @resource.attachment_file_name %><% end %></h6>
        <% end %>
        <% if !@resource.source.blank? %>
          <h6><%= link_to @resource.source, title: "Source of resource", target: "_blank" do %><i class="bi bi-link"></i> <%= @resource.source %><% end %></h6>
        <% end %>
       </div>
       <% if @resource.tags.count > 0 %>
        <div class="p-2">
          <% @resource.tags.each do |tag| %>
            <a href="<%= new_search_path(:tags => [tag.id]) %>" class="badge rounded-pill bg-dark dark-badge-link" href="#"><i class="fa fa-tags"></i> <%= tag.name %></a>
          <% end %>
        </div>
       <% end %>
       <div class="card text-bg-light m-2">
        <div class="card-body">
          <%= simple_format @resource.description %>
        </div>
      </div>
      <% if !@resource.attachment.blank? && (@resource.resource_type == 'PDF' || @resource.resource_type == 'Image' || @resource.attachment_content_type == 'video/mp4') %>
        <div class="card text-bg-light m-2">
          <% if @resource.resource_type == 'PDF' %>
            <iframe src=<%=download_resource_path(id: @resource.url)%> width="100%" height="800px" />
          <% elsif @resource.resource_type == 'Image' %>
            <%= image_tag download_resource_path(id: @resource.url) %>
          <% elsif @resource.attachment_content_type == 'video/mp4' %>
            <%= video_tag([download_resource_path(id: @resource.url)], :controls => true) %>
          <% end %>
        </div>
      <% end %>
     </div>
   </div>

  </div>
</section><!-- End About Section -->