config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #mount Ckeditor::Engine => '/ckeditor'
  resources :banners
  get 'survey/index'
  get 'survey/done'
  get 'service/index'
  resources :denial_reasons, path: 'admin/denial_reasons'
  get 'moderator/index', to: 'moderator#index', as: :moderate_submissions
  get 'moderator/approve', to: 'moderator#approve', as: :approve_submission
  get 'moderator/denial', to: 'moderator#denial', as: :denial_submission
  post 'moderator/deny', to: 'moderator#deny', as: :deny_submission
  get 'moderator/denied', to: 'moderator#denied', as: :denied_submissions
  get 'moderator/users', to: 'moderator#users', as: :moderator_users

  resources :activities

  get 'resourcings/remove_resourcing', to: 'resourcings#remove_resourcing', as: :remove_resourcing
  resources :resourcings
  get 'resources/log_event', to: 'resources#log_event', as: :log_event
  get 'resources/download', to: 'resources#download', as: :download_resource

  resources :user_types, path: 'admin/user_types'
  resources :organization_types, path: 'admin/organization_types'

  #mount RailsAdmin::Engine => '/cpanel', as: 'rails_admin'

  #resources :batches
  #resources :categories
  resources :tags, path: 'admin/tags'
  get 'tags/guide', to: 'tags#show_guide', as: :show_guide
  resources :tag_types, path: 'admin/tag_types'
  resources :featured_searches
  resources :announcements, path: 'admin/announcements'
  get 'announcements', to: 'announcements#public_announcements', as: :public_announcements
  get 'announcements/:id', to: 'announcements#show_announcement', as: :show_announcement

  resources :cops, path: 'admin/cops'
  get 'cops/:id', to: 'cops#show_cop', as: :show_cop
  get 'cop_event_email_info/:id', to: 'cops#show_event_email_info', as: :cop_event_email_info
  get 'cop_email_info/:id', to: 'cops#show_email_info', as: :cop_email_info
  
  resources :events, path: 'admin/events'
  get 'events', to: 'events#public_events', as: :public_events
  get 'events/:id', to: 'events#show_event', as: :show_event

  get 'faq/index', to: 'faq#index', as: :faq
  resources :users_organizations
  put 'usersorganizations/update_org_role', to: 'users_organizations#update_org_role', as: :update_org_role

  get 'data/csv', to: 'data#csv', as: :data_csv
  #get 'contact', to: 'contact#index', as: :contact
  #get "contact/index"
  get 'about', to: 'about#index', as: :about
  get 'about/types', to: 'about#types', as: :about_resource_types
  get 'about/new_users', to: 'about#new_users', as: :new_users
  get 'about/disclaimer', to: 'about#disclaimer', as: :disclaimer
  get 'about/access_denied', to: 'about#access_denied', as: :access_denied
  get 'about/index'
  get 'admin/index'
  post 'admin/invite_user', to: 'admin#invite_user', as: :invite_user
  get 'admin/contest', to: 'admin#contest', as: :admin_contest
  get 'admin/resource_ratings', to: 'admin#resource_ratings', as: :resource_ratings
  get 'admin/collection_ratings', to: 'admin#collection_ratings', as: :collection_ratings
  get 'admin/survey_report', to: 'admin#survey_report', as: :survey_report
  get 'admin/contest_report', to: 'admin#contest_report', as: :contest_report
  get 'admin/access_report', to: 'admin#access_report', as: :access_report
  #get 'admin/manage_tags', to: 'admin#manage_tags', as: :manage_tags
  #get 'admin/delete_tag', to: 'admin#delete_tag', as: :delete_tag
  #get 'admin/edit_tag', to: 'admin#edit_tag', as: :edit_tag
  #get 'admin/new_tag', to: 'admin#new_tag', as: :new_tag
  #post 'admin/update_tag', to: 'admin#update_tag', as: :update_tag
  get 'admin/orgs', to: 'admin#orgs', as: :orgs
  get 'admin/upload_files', to: 'admin#upload_files', as: :upload_files
  get 'admin/private_resources', to: 'admin#private_resources', as: :private_resources
  get 'admin/pending_submissions', to: 'admin#pending_submissions', as: :pending_submissions
  post 'admin/process_uploaded_files', to: 'admin#process_uploaded_files', as: :process_uploaded_files
  get 'admin/fix_resource_collections_menu', to: 'admin#fix_resource_collections_menu', as: :fix_resource_collections_menu
  get 'admin/fix_resource_collections', to: 'admin#fix_resource_collections', as: :fix_resource_collections

  #get 'ViewerJS', :to => redirect('/ViewerJS/index.html')
  get 'resources/rate_resource', to: 'resources#rate_resource', as: :rate_resource
  get 'resources/not_found', to: 'resources#not_found', as: :resources_not_found
  get 'resources/preview/:id', to: 'resources#preview', as: :resource_preview
  resources :resources

  get 'searches/update_search', to: 'searches#update_search', as: :update_search
  resources :searches

  get 'collections/not_found', to: 'collections#not_found', as: :collections_not_found
  get 'collections/rate_collection', to: 'collections#rate_collection', as: :rate_collection
  resources :collections do
    resources :resourcings
  end
  get 'about/no_approved_org', to: 'about#no_approved_org', as: :no_approved_orgs

  resources :types

  resources :licenses

  get 'organizations/not_found', to: 'organizations#not_found', as: :organization_not_found
  get 'organizations/add_user/:organization', to: 'organizations#add_user', as: :organization_add_user
  get 'organizations/apply', to: 'organizations#apply', as: :organization_apply
  get 'organizations/edit_user/:userorg', to: 'organizations#edit_user', as: :users_organizations_edit_role
  get 'organizations/approve_organization/:organization', to: 'organizations#approve_organization', as: :organization_approve
  get 'organizations/process_application', to: 'organizations#process_application', as: :organization_process_application
  match 'organizations/process_application_denial' => 'organizations#process_application_denial', :as => :organizations_process_application_denial, :via => 'post'
  match 'organizations/add_user/:organization' => 'organizations#process_new_user', :as => :organizations_process_user, :via => 'post'
  post 'organizations/invite_user', to: 'organizations#invite_user', as: :org_invite_user
  get 'organizations/private_resources/:id', to: 'organizations#private_resources', as: :org_private_resources
  resources :organizations, path: '/admin/organizations'
  get 'organizations/:id', to: 'organizations#show'
  put 'organizations/deactivate/:id', to: 'organizations#deactivate', as: 'deactivate_organization'
  put 'organizations/reactivate/:id', to: 'organizations#reactivate', as: 'reactivate_organization'
  get 'user_orgs_index', to: 'organizations#user_orgs_index', as: 'user_orgs_index'

  root :to => 'home#index'
  get 'home/error', to: 'home#error', as: :error_page
  get 'tags/:tag', to: 'tags#index', as: :collection_tags
  post 'users/save_subscriptions/:id', to: 'users#save_subscriptions', as: :user_save_subscriptions
  post 'users/remove_subscription/:id', to: 'users#remove_subscription', as: :user_remove_subscription
  get 'users/unlock_user/:id', to: 'users#unlock_user', as: :unlock_user
  get 'users/get_users', to: 'users#get_users', as: :get_users
  get 'users/export', to: 'users#export', as: :users_export
  get 'request_invite', to: 'users#request_invite', as: :request_invite
  post 'users/send_invite', to: 'users#send_invite', as: :send_invite
  devise_for :users, :controllers => {:registrations => 'registrations'}, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users, path: 'admin/users'
  put 'users/deny/:id', to: 'users#deny', as: 'deny_user'
  put 'users/deactivate/:id', to: 'users#deactivate', as: 'deactivate_user'
  put 'users/reactivate/:id', to: 'users#reactivate', as: 'reactivate_user'
  put 'users/remove_membership', to: 'users#remove_membership', as: :remove_membership
  put 'users/update_role', to: 'users#update_role', as: :update_role
  put 'users/remove_cop_membership', to: 'users#remove_cop_membership', as: :remove_cop_membership
  get '/unsubscribe', to: 'users#unsubscribe'


  #HEALTHCHECK
  get '/healthcheck', to: 'healthcheck#check_db'

  # Return 404 for any unmatched paths except those bound for Rails-provided actions
  match '*path', to: redirect('/404'), via: :all, constraints: lambda { |req|
    req.path !~ %r{^/rails}
  }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    @page_title = "About This Portal"
  end

  def no_approved_org
    add_crumb "Cannot Add Resources"
    @page_title = "Cannot Add Resources"
  end

  def access_denied
    add_crumb "Access Limited"
    @page_title = "Access Limited"
  end

  def types
    add_crumb "About", about_path
    add_crumb "Resource Types"
    @page_title = "Resource Types"
  end

  def new_users

  end

  def disclaimer
    @page_title = "Disclaimer"
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/access_denied.html.erb
<!--=== Content Part ===-->
<div class="container content">
  <div class="row">
    <div class="col-sm-12">
      <div class=" text-center">
      <h4>You are not able to access this section</h4>
      </div>
    </div>
  </div>
</div>

app/views/about/disclaimer.html.erb
<!--=== Content Part ===-->
<div class="container content">
  <div class="row blog-page">
      <!-- Bordered Funny Boxes -->
      <div class="funny-boxes funny-boxes-right-u">
        <div class="row">
          <div class="col-md-3 funny-boxes-img text-center">
            <span class="glyphicon glyphicon-info-sign" style="font-size: 100px; color:#95A5A6;"></span>
          </div>
          <div class="col-md-9">
            <p>&nbsp;</p>
            The views expressed on this web site do not necessarily reflect the views of the United States Agency for International Development or the United States Government.
          </div>
        </div>
      </div>
      <!-- End Bordered Funny Boxes -->

  </div><!--/row-->
</div><!--/container-->
<!--=== End Content Part ===-->

app/views/about/index.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
          <li><%= link_to root_path do %>Home<% end %></li>
          <li>About</li>
      </ol>
    </div>
</section><!-- End Breadcrumbs -->


<!-- ======= Services Section ======= -->
<section id="services" class="services">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5 class="border-bottom pb-2 mb-5"><i class="bi bi-envelope"></i> About This Portal</h5>

      <div class="container">
        <div class="row border-bottom pb-3 mb-3">
          <div class="col-6">
            <p>USAID/Jordan created the Jordan Development KaMP – a web-based repository of development information resources designed to improve sharing of data and information between the USAID/Jordan Mission, local implementing partners and development organizations within Jordan.</p>
            <p>The KaMP will be available to all interested development partners in Jordan and is populated with resources identified and uploaded by staff from USAID/Jordan, MESP, Implementing Partners and other portal users.</p>
            <p> Resources contained and/or referenced on the portal will include:</p>
            <ul>
              <li>USAID/Jordan templates for Implementing Partners' use in M&E and other areas</li>
              <li>Training materials and presentations developed by MESP and other organizations</li>
              <li>Assessments and evaluations conducted in Jordan and the region</li>
              <li>Geospatial data and maps</li>
              <li>Other relevant materials in a variety of formats and topics.</li>
            </ul>
          </div>
          <div class="col-6">
            <iframe width="100%" height="500px" src="https://www.youtube.com/embed/EwYX-O1HZHQ?si=qQ6plfbIJAol72hi" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
      </div>


      <div class="container">
        <div class="row border-bottom pb-3 mb-3">
          <h4>Resource Types</h4>
          <p>The Jordan Development KaMP supports uploading of a large variety of resource types, including: Documents and Spreadsheets, Comma Delimited (.csv) Files, GeoJSON Files, PDF Files, Videos and Photos.</p>

        </div>
      </div>


      <!--=== Contact Us ===-->
      <div class="container">
        <div>
          <h4>Got Questions?</h4>
          <p>If you have any questions about how the portal works, check out our <%= link_to raw("Frequently Asked Questions") , faq_path, class: "btn-u btn-u-blue one-page-btn" %> section or use the "Help" button at the top left of the screen.</p>
          <p><i class="bi bi-envelope"></i> Email us at <a href="mailto:contact@jordanmela.com" class="">contact@jordanmela.com</a></p>
        </div>
      </div>

      </div>
    </div>


  </div>
</section><!-- End Services Section -->

app/views/about/new_users.html.erb
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
          <li><%= link_to root_path do %>Home<% end %></li>
          <li>How to Contribute</li>
      </ol>
    </div>
</section><!-- End Breadcrumbs -->

<!-- ======= Services Section ======= -->
<section id="services" class="services">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5 class="border-bottom pb-2 mb-3"><i class="bi bi-envelope"></i> How to Contribute</h5>

      <p>Contributing to the portal requires being part of one of our approved partner organizations. </p>
      <p><%= link_to 'Register Now', request_invite_path %> with your partner organization.</p>
      <p>Registration is open to anyone with a valid email address.</p>
      <p>Being part of an approved partner organization means you can add resources to the portal and share them with other users in the region.</p>
      <p><%= link_to 'Existing Users Log In Here', new_session_path(resource=User) %> </p>

      </div>
    </div>


  </div>
</section><!-- End Services Section -->

app/views/about/no_approved_org.html.erb
<% content_for :title do %><%= @page_title %><% end %>
<div class="info-board info-board-red">
    <p>We're sorry. You can't add any collections right now because you're not part of an approved organization yet. </p>

    <p>You can <%= link_to 'add your own organization', new_organization_path %> or request access to an <%= link_to 'approved organization', organizations_path %></p>

</div>

app/views/about/types.html.erb
<% content_for :title do %><%= @page_title %><% end %>
<!--=== Content Part ===-->
<div class="container content">
  <div class="row service-v1 margin-bottom-40">

      <div class="shadow-wrapper">
        <blockquote class="hero box-shadow shadow-effect-2 text-center">
          <p>When viewing resources, portal users can browse the contents of certain files before they decide to download them. </p>
        </blockquote>
      </div>
  </div>

  <div class="row service-v1 margin-bottom-40">
        <div class="col-md-8">
          <h2><i class="fa fa-files-o"></i> Documents and Spreadsheets</h2>
          <p>Documents and Spreadsheets offer a preview box allowing users to browse through and search the file before downloading it</p>
          <p>Documents include files such as Microsoft Word and Powerpoint, while spreadsheets include most common spreadsheet formats such as Microsoft Excel</p>
        </div>
        <div class="col-md-4">
          <img class="img-responsive" src="/document_preview.png" width="100%" alt="Sample Preview of Document" />
        </div>
  </div>
  <hr>
  <div class="row service-v1 margin-bottom-40">
        <div class="col-md-4">
          <img class="img-responsive" src="/csv_preview.png" width="100%" alt="Sample Preview of a CSV document" />
        </div>
        <div class="col-md-8">
          <h2><i class="fa fa-file-text-o"></i> Comma Delimited Files</h2>
          <p>Data is commonly transferred or exported to CSV (Comma Separated Values) format. Resource that are in .CSV format will generate a table showing the data contained in the file along with sorting and searching tools to browse it. </p>
          <h4>Latitude/Longitude</h4>
          <p>CSV files that have columns labeled "latitude" and "longitude" will also show a "Map" tab that overlays the file's rows onto a map.</p>
        </div>
  </div>
  <hr>
  <div class="row service-v1 margin-bottom-40">
        <div class="col-md-8">
          <h2><i class="fa fa-map-marker"></i> GeoJSON Files</h2>
          <p>GeoJSON is a format for encoding a variety of geographic data structures. When viewing GeoJSON resources, the data in the file will be displayed on a map.</p>
          <p>GeoJSON supports the following geometry types: Point, LineString, Polygon, MultiPoint, MultiLineString, and MultiPolygon. </p>
        </div>
        <div class="col-md-4">
          <img class="img-responsive" src="/img/map_preview.png" width="100%" alt="Sample Preview of a GeoJSON resource" />
        </div>
  </div>
  <hr>
  <div class="row service-v1 margin-bottom-40">
      <h2><i class="fa fa-file-pdf-o"></i> PDF Files</h2>
      <div class="row md-margin-bottom-40">
        <div class="col-md-10">
          <p>
            Files in PDF format will also generate previews for the user, but require installation of the free Adobe Reader plugin in their browser.</p>
          <p>
            While this plugin is built into most newer web browsers, users that are not able to see the preview can verify they have the latest version installed by clicking the Adobe Reader link
          </p>
        </div>
        <div class="col-md-2">
          <p align="center">
            <a href="http://get.adobe.com/reader/" target="_blank"><img width="158" height="39" src="/img/get_adobe_reader.png" alt="Get Acrobat Reader web logo"><br>
              Get Adobe Reader</a>
          </p>
        </div>
      </div>
  </div>


    </div>


</div><!--/container-->
<!--=== End Content Part ===-->